functions = require("lib.functions")

data:extend({
	{
		type = "cargo-wagon",
		name = "yir_cw_flourit_4a",
		icon = "__z_yira_UP__/graphics/icons/cws64_fluorite_icon_4aw.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 400,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.8,
	},

	{
		type = "cargo-wagon",
		name = "yir_cw_uran_4a",
		icon = "__z_yira_UP__/graphics/icons/cws64_uranite-icon_4aw.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 400,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.8,
	},

	{
		type = "cargo-wagon",
		name = "yir_cw_empty_4a",
		icon = "__z_yira_UP__/graphics/icons/cws64_empty_4aw.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 400,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.8,
	},

	{
		type = "cargo-wagon",
		name = "yir_cw_trans_4a",
		icon = "__z_yira_UP__/graphics/icons/cws64_up_closed_icon_4aw.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 400,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.8,
	},

	{
		type = "cargo-wagon",
		name = "yir_cw_4a_urana",
		icon = "__z_yira_UP__/graphics/icons/4aw_cw_urana_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 400,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.05,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.8,
		wheels = functions.standard_train_wheels,
	},

	{
		type = "cargo-wagon",
		name = "yir_cw_4a_cellsu",
		icon = "__z_yira_UP__/graphics/icons/4aw_cw_ucells_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 400,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.05,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.8,
		wheels = functions.standard_train_wheels,
	},
})